name: check

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Cache Deno dependencies
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-
          path: ~/.cache/deno

      - uses: jdx/mise-action@v3

      - name: Check and build
        run: mise run check:full
